logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
rv-brand = "ReVanced eXtended"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "inotia00 ReVanced"
included-patches = "'Enable music search' 'MaterialYou' 'Premium heading' 'Shorts outline button'"
excluded-patches = "'Custom branding icon Revancify Blue' 'Custom branding name YouTube' 'Enable old quality layout' 'Enable wide search bar' 'Hide account menu' 'Hide button container' 'Hide captions button' 'Hide cast button' 'Hide channel avatar section' 'Hide channel profile components' 'Hide collapse button' 'Hide comment component' 'Hide crowdfunding box' 'Hide description components' 'Hide floating microphone' 'Hide fullscreen panels' 'Hide handle' 'Hide info cards' 'Hide music button' 'Hide previous next button' 'Hide tooltip content' 'Swipe controls' 'Theme' 'Translations'"

[Music]
build-mode = "both"
app-name = "YouTube-Music"
excluded-patches = "'Custom branding icon Revancify Blue' 'Custom branding name YouTube Music' 'Enable old style library shelf' 'Enable old style miniplayer' 'Hide account menu' 'Hide action bar label' 'Hide button shelf' 'Hide carousel shelf' 'Hide cast button' 'Hide category bar' 'Hide emoji picker' 'Hide flyout panel' 'Hide handle' 'Hide navigation bar component' 'Hide new playlist button' 'Hide playlist card' 'Hide radio button' 'Hide tooltip content'"
included-patches = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytm-rvx"
apkmirror-arch = "both"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"

[Twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"
