enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
enabled = false
build-mode = "both"
excluded-patches = ""
included-patches = ""
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
enabled = false
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "both"

[Music-Extended]
enabled = false
app-name = "Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "both"

[YouTube-Extended]
enabled = false
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YouTube-Advanced]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
cli-source = "inotia00/revanced-cli"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/revanced-integrations"
rv-brand = "YT-Advanced ReVanced"
included-patches = "'MaterialYou' 'Shorts outline button'"
excluded-patches = "'Custom branding heading' 'Custom branding icon YouTube' 'Custom branding name YouTube' 'Enable old quality layout' 'Enable wide search bar' 'Swipe controls' 'Theme'"

[Music-Advanced]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
cli-source = "inotia00/revanced-cli"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/revanced-integrations"
rv-brand = "YT-Advanced ReVanced"
excluded-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music'"
